### ISSUE TITLE
clippy stopped failing CI

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#105]
child of #117 

see this build for example:

https://travis-ci.org/holochain/holochain-rust/builds/399524203?utm_source=github_status&utm_medium=notification

**Comment by lucksus** [comment]
Is this still relevant, after switching to @sphinxc0re's Docker image?

**Comment by ddd-mtl** [comment]
I merged my branch today and did not get rustfmt nor clippy errors this time. I'd say, it got fixed.

**Comment by thedavidmeister** [comment]
oh, it's not whether or not there are currently issues, but whether or not clippy failing throws a warning or error on CI (should error)

**Comment by thedavidmeister** [comment]
this is definitely still an issue, see these warnings in the green build here:

https://travis-ci.org/holochain/holochain-rust/builds/405318095#L570

**Comment by ddd-mtl** [comment]
Before it was crashing so I thought that was what you meant by 'failing'.
For me its fine like this. I would not enforce clippy until there is team agreement on using it and configuration.

**Comment by thedavidmeister** [comment]
@ddd-mtl yes we have to agree on configuration and usage for all our tools, i'm totally on board to work through a trello card for this

this ticket is more about wanting nothing to "warn" by the time we are testing a production candidate CI build. on CI every test should be deterministic and a binary fail or pass score and we don't merge anything to develop/master unless everything clearly passes CI

warnings are ok for the local/dev/experimental context, but they muddy the water when it comes to final QA for merge/deployments

this issue isn't about enforcing or not enforcing clippy, it's simply flagging that there is currently some test running on CI that doesn't have a clear pass/fail outcome

so, potential solutions i see here:

- remove clippy from CI (optional local usage)
- use new/existing clippy configuration and make it fail CI builds (optional local warnings)
- use new/existing clippy configuration but only run it on `allow_failures` builds (optional local warnings)
