### ISSUE TITLE
Conductor not logging p2p bindings to set bootstrap node

### ISSUE THREAD

**Issue by pythagorean** [holochain/holochain-rust#1156]
Using v0.0.7-alpha with n3h-0.0.7-alpha1:

Starting first node from conductor, here is the output:

```
Using config path: tmp-storage/conductor-config.toml
Unlocking agent keys:
Unlocking key for agent 'test_agent1': 
Reading agent key from conductor/holo_tester.key
Spawning network with working directory: /tmp
(n3h-bin) [w] attempting read stdin
(n3h-bin) [w] got stdin config! {"webproxy":{"connection":{"rsaBits":1024,"bind":["wss://0.0.0.0:0/"]},"wssAdvertise":"auto","wssRelayPeers":null}}
(n3h-bin) [i] executing mode HACK
(*n3hMode*) [i] @@ CONFIG @@ {
...
}
(wss-server-utils) [i] loaded rsa fingerprint jwmlPrWlJIl4O7NlRISp1MhxBM0=
(wss-connection) [i] listening at wss://127.0.0.1:57818/
Network spawned with bindings:
	 - ipc: wss://127.0.0.1:57818/
	 - p2p: []
Reading DNA from dna-src/dist/dna-src.dna.json
...
```

Since there is nothing within the p2p network bindings, there is nothing to set HC_N3H_BOOTSTRAP_NODE to in order to instantiate a second node.

**Comment by ddd-mtl** [comment]
Hello.
The p2p bindings should appear a bit lower in a log line starting with `p2p bound`.
The log line you are mentionning has been fixed [here](https://github.com/holochain/holochain-rust/pull/1149), which will be in the next release.

**Comment by pythagorean** [comment]
Problem still exists in v0.0.8-alpha, I will try to use the p2p-bound information in the meantime.

**Comment by Connoropolous** [comment]
are you using `hc run` or `holochain` @pythagorean ?

**Comment by Connoropolous** [comment]
If you're using `holochain` conductor command, you can set `n3h_log_level` to `i` in the config, and you'll see the right output
https://developer.holochain.org/guide/0.0.7-alpha/conductor_networking.html#n3h_log_level-char

**Comment by Connoropolous** [comment]
Actually, you should be able to do this regardless, by setting environment variable `N3H_LOG_LEVEL=i` (this isn't normally intended for public use)

**Comment by pythagorean** [comment]
I'm using `hc` for single-user testing and `holochain` conductor for multi-user tests. Right now using the `develop` branch I'm getting the p2p bindings where they are expected without setting a log level.

**Comment by Connoropolous** [comment]
@pythagorean did you see in the latest dev pulse this got fixed?
"3. Network Bootstrapping: ‘P2P Ready’ Message"
https://medium.com/holochain/continued-cryptography-and-important-optimizations-4867d777de94

Can you close if your issue is resolved?

**Comment by pythagorean** [comment]
Thanks, yes it is resolved.
